---
title: "Schedule"
description: |
 Schedule and course materials for Animal Physiology (Zool 430/430L Fall 2023).
tbl-colwidths: [9,3, 20, 20,30]
---
```{r}
#| echo: false
```

## Assignment Schedule _SUBJECT TO CHANGE_


::: column-page
|   |   | Class Topic | Assignment Due  | Lab | 
|----|----|----|----|----|
|Week 1|||||
| 8/21  | M | Intro to Course |   |   |   
| | W | Heavyweight Whale Discussion \[[html](posts/2023-08-23-the-colossal-whale/index.qmd)\] \[[paper](https://www.nature.com/articles/s41586-023-06381-1)\]  | (Reading Assessment)  | Lab1: PC1-G-HR/Data analysis \[[overview](labs/Lab1-heart-rate-and-data-analysis/index.qmd)\] \[[lab manual](labs/Lab1-heart-rate-and-data-analysis/Lab1-data-aquistion-finger-pulse.pdf)\] \[[protocol](labs/Protocols/p1-intro-finger-pulse.pdf)\] |   
|   | F | Library Day - Meet at Hamilton \[[html](posts/2023-08-25-Library-day/index.qmd)\] |   |   |   
|Week 2|||||
| 8/28  | M | Metabolism \[[html](posts/2023-08-28-Metabolism/index.qmd)\] \[[reading assignment and questions](discussions/Discussion_Week_2.pdf)\] \[[HWA readings](https://drive.google.com/drive/folders/1ONGdTPdeQz2lgGgAiWyZ_yGRmmcNSwoV)\] |   |   |   
| | W | Size and Scaling \[[podcast](https://youtu.be/_NDNa_3Bon8)\]|   | Lab2: PC2-G-Honolulu Zoo \[[lab manual](labs/Lab2-zoo/index.qmd)\] |   
|   | F | Adjustments to Metabolism | PS1: Metabolism \[[pdf](homework/HW1metabolism.pdf)\]|   |   
|Week 3|||||
| 9/4 | M | Labor Day Holiday | Choose your Fossil  |   |   
| | W | Temperature \[[html](posts/2023-09-06-Temperature/index.qmd)\] \[[discussion](discussions/Discussion_Week_3_temperature.pdf)\] |   | Lab3:PC3-IWS-Peripheral Circ/Dive Resp \[[overview](labs/Lab3-human-peripheral-circulation-dive-response/Lab3.qmd)\]  |   
|   | F | Iterative Method  | |   |   
|Week 4|||||
| 9/11  | M | Heterothermy (see last week)/Cardiac Function \[[html](posts/2023-09-11-cardiac-function/cardiac.qmd)\]  | PS2: Temperature \[[pdf](homework/HW2heat_temp.pdf)\]   |   | 
| | W | Cardiac Regulation | Background Design 1 \[[html](projects/2023-09-06-design-background/index.qmd)\] | Lab Practical / Lab4: PC3-G-ECG/Cardiac Function \[[overview](labs/Lab4-human-ecg/Lab4.qmd)\] |   
|   | F | Design 1 chat |   |     
|Week 5|||||
| 9/18  | M | Sustained Metabolic Scope Paper \[[discussion](discussions/Discussion-Week4-metabolic-ceiling.pdf)\] \[[Hammond and Diamond 1997](https://drive.google.com/drive/u/1/folders/1psPVIMIJVUuySxp9MHSQxxAhlvy-O9kK)\],  \[[optional: Peterson et al. 1990](https://drive.google.com/drive/u/1/folders/1psPVIMIJVUuySxp9MHSQxxAhlvy-O9kK)\] |  |   |   
| | W | Feeding  \[[html](posts/2023-09-18-feeding/feeding.qmd)\] \[[discussion](discussions/Discussion-Week5-feeding&digestion.pdf)\]|  | Lab5: PC1-IWS-Toad Heart \[[overview](labs/Lab5-toad-heart/Lab5.qmd)\]|   
|   | F | Design 1 workshop - bring your draft |   |   |   
|Week 6|||||
| 9/25  | M | Digestion  \[[html](posts/2023-09-25-digestion/digestion.qmd)\] \[[discussion](discussions/Discussion-Week5-feeding&digestion.pdf)\]| Design 1 Report Due \[[assignment](projects/design1.qmd)\] \[[pdf](projects/1.MetabolismTempDesign1.pdf)\] \[[turn in](projects/design1-turnin.qmd)\]   | 
| | W | Specialized Digestive Systems  |  Peer Critique 1 \[[turn in](projects/design1-turnin.qmd)\] | Design Critique Session   |   
|   | F | Max Size Herbivores Paper Claus 2003   | |   |   
|Week 7|||||
| 10/2  | M | Neurons  \[[html](posts/2023-10-02-neurons/neurons.qmd)\] \[[discussion](discussions/Discussion-Week7-neurons-signal-propagation.pdf)\] |     |   |   
|| W | Synapses/Signal Propagation | Design 1 Rewrite Due  |  Lab6: PC2-G-Lobster Heart \[[overview](labs/Lab6-lobster-heart/Lab6.qmd)\]| 
|   | F | Sensory Receptors I |   |   |   
|Week 8|||||
| 10/9  | M | Sensory Receptors II  | PS3: Feeding & Digestion \[[pdf](homework/HW3feeding_digestion.pdf)\] |  |   
| | W | Muscles |   |  Lab 7:PC1-G-Vertebrate Action Potential |   
|   | F | Muscles II  |   |   |   
|Week 9|||||
| 10/16 | M | Motor Control | Design 2 Feeding & Digestion |   |   
| | W | Biomechanics  | Peer Critique 2 |  Design Presentations  |   
|   | F | Biomechanics  | PS4: Neurons   |   |   
|Week 10|||||
| 10/23 | M | Locomotion on Land  |  |   |   
|   | W | Locomotion in Fluids  |  Rewrite Design 2 Due | Lab8: PC2-G-Human Muscle  |   
|   | F | Blood |    |   |   
|Week 11|||||
| 10/30 | M | Ventilation   |  PS5: Muscles & Biomech |   |  
|   | W | Aquatic Respiration |   | Lab9: PC3-G-Toad Muscle  |   
|   | F | Aerial Respiration  |   |   |   
|Week 12|||||
| 11/6  | M | Symmorphosis: Weibel, Taylor, and Hoppeler (1991) The concept of symmorphosis: A testable hypothesis of structure-function relationship. PNAS 88:10357-61 |  PS6: Respiration |   |   
|  | W | Osmoregulation  |   | Lab10:PC1-I-Toad Muscle Independent |   
|   | F | Veterans Day Holiday  |   |   |   
|Week 13|||||
| 11/13 | M | Excretion | Design 3 Resipration  |   |   
|   | W | Excretion | Peer Critique 3 | Lab 11: PC1-G-Human EEG  |   
|   | F | Hormonal Control  |   |   |   
|Week 14|||||
| 11/20 | M | Reproduction  | PS7: Osmoregulation |   |   
|   | W | Thanksgiving Holiday  | Design 3 Rewrite  | No Labs |   
|   | F | Thanksgiving Holiday  |   |   |   
|Week 15|||||
| 11/27 | M | Immune System |   |   |   
|   | W | Immune System | Design 4: Osmoreg/Own | Lab 12: PC2-G-Human Renal  |   
|   | F | Student Presentations |   |   |   
|Week 16|||||
| 12/4  | M | Student Presentations |   |   |   
|  | W | Student Presentations |   | Turn in Lab 12  |   
||||||
| 12/11 | M | Finals Week | Design Term Paper Due |   |   
||||||
:::





