---
title: "3. Temperature"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Heat and its implications for physiology"
date: 2023-09-06
format: 
  html: default 
  pdf: default
categories: [module 3, week 3, BMR, SMR, RMR, AMR, DMR ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Withers chapter 5. Look over the homework, handout, and discussion questions and skim the chapter, reading anything that you need to know.  
2. \[[Discussion Questions](../../discussions/Discussion_Week_3_temperature.pdf)\] 
3. \[[Slide Deck](../../powerpoints/3.Temperature.pdf)\] - for your reference as we go through the material
:::

### Announcements/Reminders

-  Monday is Labor Day. No class


### Week 3 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
| 1 | Justin  | Morgan  | Richard |
| 2 | Adry   |  Matthew | Logan B |
| 3 | Mayuka |  Krystal | Logan M |
| 4 | Anna  | Garrett  | Sasha |
| 5 | Kirsten  | Christina  | Kylie |
| 6 | Maisie   | Alvin  | Jessica |
   
   
# 3. Temperature

## Modes of Heat Transfer

{{< video https://youtu.be/BHchDrboqEo >}}


## Q10 

{{< video https://youtu.be/T5O9UvSZ_-g >}}

## Iterative Method

{{< video https://youtu.be/pEzcZCTYPyE >}}


# For Next Time



::: callout-note
## Reminders and materials

:::


